### ISSUE TITLE
precision

### ISSUE THREAD

**Issue by DVridovic** [tensaix2j/binacpp#2]
Hi

Thank you for sharing this code. I encountered one issue: to_string function that you use in your BinaCPP class formats double precision numbers to only six decimal digits. This cannot be changed. So if I want to buy for instance TRX/BTC at, say, 0.00000353, this price will be rounded up to 0.000004, and I will overpay (fortunately I tried with the minial amount :). Anyway, this can be fixed easily: just add
```
   template<typename T> static std::string to_string(T val)
   {
      return std::to_string(val);
   }

   static std::string to_string(double val)
   {
      std::ostringstream out;
      out.precision(8);
      out.setf(std::ios_base::fixed);
      out << val;
      return out.str();
   }
```
to the private section of BinaCPP. You'll also need to include sstream.

It would also be good to surround the entire context of binacpp.h with
```
#ifndef BINACPP_H
#define BINACPP_H
...
#endif
```
so it can be included from anywhere.

**Comment by tensaix2j** [comment]
Added. Thanks. 
https://github.com/tensaix2j/binacpp/commit/08d61ba3642da21198febb1ba205dac5fc24e070
